export enum Icons {
	arrowLeft = 'arrow-left',
	arrowRight = 'arrow-right',
	arrowUp = 'arrow-up',
	arrowUpFill = 'arrow-up-fill',
	arrowDown = 'arrow-down',
	arrowDownFill = 'arrow-down-fill',
	filterCrisis = 'filter-crisis',
	filter = 'filter',
	month = 'month',
	quaterYear = 'quater-year',
	halfYear = 'half-year',
	year = 'year',
	trendUp = 'trend-up',
	trendDown = 'trend-down',
	possessionsInfo = 'possessions-info',
	possessionsInvestments = 'possessions-investments',
	possessionsDocuments = 'possessions-documents',
	possessionsNoise = 'possessions-noise',
}
